# Generated by Django 5.1.6 on 2025-03-06 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_client_author_alter_schedule_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobDate', models.DateField()),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('uncomplete', 'Uncomplete')], default='uncomplete', max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.schedule')),
            ],
        ),
    ]
