# Generated by Django 5.1.6 on 2025-03-06 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.schedule'),
        ),
    ]
