# Generated by Django 5.1.6 on 2025-03-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_job_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
