# Generated by Django 5.1.6 on 2025-03-20 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_invoice_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='client',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
