# Generated by Django 5.1.6 on 2025-03-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentType',
            field=models.CharField(choices=[('Cash', 'cash'), ('Check', 'check'), ('Zelle', 'zelle'), ('Card', 'card')], max_length=10),
        ),
    ]
