# Generated by Django 5.1.6 on 2025-03-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_payment_paymenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentType',
            field=models.CharField(choices=[('Cash', 'cash'), ('Check', 'check'), ('Zelle', 'zelle'), ('Card', 'card')], default='cash', max_length=50),
        ),
    ]
