# Generated by Django 5.1.6 on 2025-03-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_payment_paymenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentType',
            field=models.CharField(default='cash', max_length=50),
        ),
    ]
