# Generated by Django 5.1.6 on 2025-05-21 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_balancehistory'),
        ('api', '0018_alter_payment_paymentdate'),
    ]

    operations = [
    ]
