# Generated by Django 5.1.6 on 2025-05-21 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_balance_balance_adjustment_balanceadjustment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balanceadjustment',
            old_name='Client',
            new_name='client',
        ),
    ]
