# Generated by Django 5.1.6 on 2025-06-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_client_balanceadjustment_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancehistory',
            name='service_month',
            field=models.PositiveSmallIntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balancehistory',
            name='service_year',
            field=models.PositiveSmallIntegerField(default=2025),
            preserve_default=False,
        ),
    ]
