# Generated by Django 5.1.6 on 2025-06-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_balancehistory_service_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancehistory',
            name='service_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancehistory',
            name='service_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
