# Generated by Django 5.1.6 on 2025-06-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_balancehistory_service_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=6),
        ),
    ]
