# Generated by Django 5.1.6 on 2025-06-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_userprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('BOSS', 'Boss'), ('WORKER', 'Worker'), ('VIEWER', 'VIEWER')], default='BOSS', max_length=50),
        ),
    ]
