# Generated by Django 5.1.6 on 2025-06-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Order of the job. Must be a positive number.', null=True),
        ),
    ]
