# Generated by Django 5.1.6 on 2025-09-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_schedule_schedule_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['schedule_day', 'order']},
        ),
        migrations.AddField(
            model_name='schedule',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
