# Generated by Django 5.1.12 on 2025-09-18 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_jobnote_job_alter_propertynote_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobnote',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.job'),
        ),
        migrations.AlterField(
            model_name='propertynote',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.property'),
        ),
        migrations.AlterField(
            model_name='schedulenote',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.schedule'),
        ),
    ]
