# Generated by Django 5.1.12 on 2025-09-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_jobnote_job_alter_propertynote_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobnote',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertynote',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schedulenote',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
