# Generated by Django 5.1.12 on 2025-09-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_jobnote_title_alter_propertynote_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobnote',
            name='content',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertynote',
            name='content',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schedulenote',
            name='content',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
