# Generated by Django 5.1.12 on 2025-09-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_jobnote_content_alter_propertynote_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobnote',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='propertynote',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='monthly_pricing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedulenote',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
